(ns top.kzre.homunculus.core.types.inline-lift.methods
  (:require [top.kzre.homunculus.core.types.inline-lift.methods.call]
            [top.kzre.homunculus.core.types.inline-lift.methods.let]
            [top.kzre.homunculus.core.types.inline-lift.methods.lambda]
            [top.kzre.homunculus.core.types.inline-lift.methods.block]
            [top.kzre.homunculus.core.types.inline-lift.methods.if]
            [top.kzre.homunculus.core.types.inline-lift.methods.loop]
            [top.kzre.homunculus.core.types.inline-lift.methods.define]
            [top.kzre.homunculus.core.types.inline-lift.methods.while]
            [top.kzre.homunculus.core.types.inline-lift.methods.try]
            [top.kzre.homunculus.core.types.inline-lift.methods.catch]
            [top.kzre.homunculus.core.types.inline-lift.methods.throw]
            [top.kzre.homunculus.core.types.inline-lift.methods.assign]
            [top.kzre.homunculus.core.types.inline-lift.methods.vector]
            [top.kzre.homunculus.core.types.inline-lift.methods.map]
            [top.kzre.homunculus.core.types.inline-lift.methods.literal]
            [top.kzre.homunculus.core.types.inline-lift.methods.variable]
            [top.kzre.homunculus.core.types.inline-lift.methods.default]))