(ns top.kzre.homunculus.core.types.lambda-elim.methods
  (:require [top.kzre.homunculus.core.types.elaborate.methods.call]
            [top.kzre.homunculus.core.types.elaborate.methods.let]
            [top.kzre.homunculus.core.types.elaborate.methods.lambda]
            [top.kzre.homunculus.core.types.elaborate.methods.block]
            [top.kzre.homunculus.core.types.elaborate.methods.if]
            [top.kzre.homunculus.core.types.elaborate.methods.loop]
            [top.kzre.homunculus.core.types.elaborate.methods.define]
            [top.kzre.homunculus.core.types.elaborate.methods.while]
            [top.kzre.homunculus.core.types.elaborate.methods.try]
            [top.kzre.homunculus.core.types.elaborate.methods.catch]
            [top.kzre.homunculus.core.types.elaborate.methods.throw]
            [top.kzre.homunculus.core.types.elaborate.methods.assign]
            [top.kzre.homunculus.core.types.elaborate.methods.vector]
            [top.kzre.homunculus.core.types.elaborate.methods.map]
            [top.kzre.homunculus.core.types.elaborate.methods.literal]
            [top.kzre.homunculus.core.types.elaborate.methods.variable]))