(ns top.kzre.homunculus.core.types.recur-elim.methods
  (:require [top.kzre.homunculus.core.types.recur-elim.methods.loop]
            [top.kzre.homunculus.core.types.recur-elim.methods.let]
            [top.kzre.homunculus.core.types.recur-elim.methods.lambda]
            [top.kzre.homunculus.core.types.recur-elim.methods.block]
            [top.kzre.homunculus.core.types.recur-elim.methods.if]
            [top.kzre.homunculus.core.types.recur-elim.methods.call]
            [top.kzre.homunculus.core.types.recur-elim.methods.assign]
            [top.kzre.homunculus.core.types.recur-elim.methods.while]
            [top.kzre.homunculus.core.types.recur-elim.methods.try]
            [top.kzre.homunculus.core.types.recur-elim.methods.catch]
            [top.kzre.homunculus.core.types.recur-elim.methods.throw]
            [top.kzre.homunculus.core.types.recur-elim.methods.vector]
            [top.kzre.homunculus.core.types.recur-elim.methods.map]
            [top.kzre.homunculus.core.types.recur-elim.methods.define]
            [top.kzre.homunculus.core.types.recur-elim.methods.literal]
            [top.kzre.homunculus.core.types.recur-elim.methods.variable]
            [top.kzre.homunculus.core.types.recur-elim.methods.recur]
            [top.kzre.homunculus.core.types.recur-elim.methods.default]))